
apiVersion: v1
kind: Pod
metadata:
  name: pod-pdv
spec:
  containers:
    - name: nginx-container-1
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: primeiro-pv
  volumes:
    - name: primeiro-pv
      persistenceVolumeClaim:
        path: my-pvc
